<?xml version="1.0"?>

<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->

<xacro:property name="PI" value="3.1415926535897931"/>

<xacro:property name="chassisHeight" value="0.1" />
<xacro:property name="chassisLength" value="0.4"/>
<xacro:property name="chassisWidth" value="0.2"/>
<xacro:property name="chassisMass" value="50"/>

<xacro:property name="laserPosHeight" value="0.15"/>

<xacro:property name="wheelWidth" value="0.02"/>
<xacro:property name="wheelRadius" value="0.05"/>
<xacro:property name="wheelPos" value="0.2"/>
<xacro:property name="wheelMass" value="5"/>

<xacro:property name="cameraSize" value="0.05"/>
<xacro:property name="cameraMass" value="0.1"/>

<xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
<xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
<xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />
 
<link name="base_link" />

<joint name="base_joint" type="fixed">
  <parent link="base_link"/>
  <child link="chassis"/>
  <origin xyz="${-chassisLength/2} 0 0" rpy="0 0 0" />
  <axis xyz="1 0 0" rpy="0 0 0" />  
</joint>

<link name='chassis'>
  <collision> 
    <origin xyz="0 0 ${wheelRadius+chassisHeight/2}" rpy="0 0 0"/> 
    <geometry> 
      <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
    </geometry> 
  </collision>
  <visual> 
    <origin xyz="0 0 ${wheelRadius+chassisHeight/2}" rpy="0 0 0"/> 
    <geometry> 
      <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
    </geometry> 
    <material name="orange"/>
  </visual>
  <inertial> 
    <origin xyz="0 0 ${wheelRadius+chassisHeight/2}" rpy="0 0 0"/> 
    <mass value="${chassisMass}"/> 
    <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
  </inertial>
</link>

<wheel lr="left_front" tX="0.6" tY="1"/>
<wheel lr="right_front" tX="0.6" tY="-1"/>
<wheel lr="left_back" tX="-0.6" tY="1"/>
<wheel lr="right_back" tX="-0.6" tY="-1"/>

<joint name="hokuyo_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="0 0 ${laserPosHeight}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="hokuyo_link"/>
</joint>

<!-- Hokuyo Laser -->
<link name="hokuyo_link">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
  <box size="0.1 0.1 0.1"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="/home/tdvu/.gazebo/models/hokuyo/meshes/hokuyo.dae"/>
    </geometry>
  </visual>

  <inertial>
    <mass value="1e-5" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
  </inertial>
</link>  

</robot>

